// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210613073522_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("API.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EndTime")
                        .HasColumnType("int");

                    b.Property<string>("Fen")
                        .HasColumnType("longtext");

                    b.Property<string>("Opponent")
                        .HasColumnType("longtext");

                    b.Property<string>("Pgn")
                        .HasColumnType("longtext");

                    b.Property<bool>("Rated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Result")
                        .HasColumnType("longtext");

                    b.Property<string>("Rules")
                        .HasColumnType("longtext");

                    b.Property<string>("TimeClass")
                        .HasColumnType("longtext");

                    b.Property<string>("TimeControl")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
